name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: both

          - release_for: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: both

          - release_for: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            command: build

          - release_for: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            command: build

          - release_for: Windows-x86
            os: windows-latest
            target: i686-pc-windows-msvc
            command: build

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0

        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Build archive
        shell: bash
        run: |
          binary_name="blowout"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.platform.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.platform.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.platform.target }}/release/$binary_name" "$dirname"
          fi

          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
